-- Users table for authentication and authorization
CREATE TABLE IF NOT EXISTS USER (
  USER_ID INT PRIMARY KEY AUTO_INCREMENT,
  USERNAME VARCHAR(50) UNIQUE NOT NULL,
  EMAIL VARCHAR(255) UNIQUE NOT NULL,
  PASSWORD_HASH VARCHAR(255) NOT NULL,
  ROLE ENUM('admin', 'organizer', 'attendee') DEFAULT 'attendee',
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Venues table for event locations
CREATE TABLE IF NOT EXISTS VENUE (
  VENUE_ID INT PRIMARY KEY AUTO_INCREMENT,
  VENUE_NAME VARCHAR(255) NOT NULL,
  ADDRESS TEXT NOT NULL,
  CAPACITY INT,
  CONTACT_INFO VARCHAR(255),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Categories for event types
CREATE TABLE IF NOT EXISTS CATEGORY (
  CATEGORY_ID INT PRIMARY KEY AUTO_INCREMENT,
  CATEGORY_NAME VARCHAR(100) UNIQUE NOT NULL,
  DESCRIPTION TEXT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Improved Events table with foreign keys
CREATE TABLE IF NOT EXISTS EVENT (
  EVENT_ID INT PRIMARY KEY AUTO_INCREMENT,
  EVENT_NAME VARCHAR(255) NOT NULL,
  EVENT_DATE DATETIME NOT NULL,
  LOCATION VARCHAR(255),
  DESCRIPTION TEXT,
  ORGANIZER_ID INT,
  VENUE_ID INT,
  CATEGORY_ID INT,
  CAPACITY INT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (ORGANIZER_ID) REFERENCES USER(USER_ID) ON DELETE SET NULL,
  FOREIGN KEY (VENUE_ID) REFERENCES VENUE(VENUE_ID) ON DELETE SET NULL,
  FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID) ON DELETE SET NULL
);

-- Updated Attendees table with user linkage
CREATE TABLE IF NOT EXISTS ATTENDEE (
  ATTENDEE_ID INT PRIMARY KEY AUTO_INCREMENT,
  USER_ID INT,
  NAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255),
  NUMBER VARCHAR(15) NOT NULL,
  EVENT_ID INT NOT NULL,
  STATUS ENUM('registered', 'confirmed', 'cancelled', 'attended') DEFAULT 'registered',
  REGISTERED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE SET NULL,
  FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID) ON DELETE CASCADE
);
