CREATE TABLE EVENT (
  EVENT_ID INT PRIMARY KEY AUTO_INCREMENT,
  EVENT_NAME VARCHAR(255) NOT NULL,
  EVENT_DATE DATETIME NOT NULL,
  LOCATION VARCHAR(255),
  DESCRIPTION TEXT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE ATTENDEE (
  ATTENDEE_ID INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255),
  NUMBER VARCHAR(15) NOT NULL,
  EVENT_ID INT NOT NULL,
  STATUS VARCHAR(50) DEFAULT 'registered',
  REGISTERED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID) ON DELETE CASCADE
);
